config/routes.rb
Rails.application.routes.draw do

  root to: "static_pages#root"
  
  resource :session
  resources :users
  
  namespace :api, defaults: {format: :json} do
    resources :texts
    resources :critiques
    resources :users
    resources :replies
    resources :comments
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :user_id, :text_id, :content, presence: true
  
  belongs_to :user
  belongs_to :text
end

app/models/critique.rb
class Critique < ActiveRecord::Base
  validates :user_id, :text_id, :content, :start_idx, :end_idx, presence: true
  
  belongs_to :text
  belongs_to :user
  has_many :replies, dependent: :destroy
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  validates :content, :user_id, :critique_id, presence: true
  
  belongs_to :user
  belongs_to :critique
end

app/models/text.rb
class Text < ActiveRecord::Base
  validates :user_id, :title, :content, presence: true
  
  belongs_to :user
  has_many :critiques, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  
  before_validation :ensure_session_token
  
  has_many :texts, dependent: :destroy
  has_many :critiques, dependent: :destroy
  has_many :replies, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  
  attr_reader :password
  
  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64
  end
  
  def reset_session_token
    self.session_token = SecureRandom::urlsafe_base64
    self.save
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end
end

app/controllers/api/replies_controller.rb
class Api::RepliesController < ApplicationController
  
  def create
    @reply = Reply.new(reply_params)
    
    if @reply.save
      render json: @reply
    else
      render json: @reply.errors.full_messages
    end
  end
  
  def show
    @reply = Reply.find(params[:id])
    
    render :show
  end
  
  def destroy
    @reply = Reply.find(params[:id])
    
    if @reply.destroy
      render json: @reply
    else
      render json: @reply.errors.full_messages
    end
  end
  private
  def reply_params
    params.require(:reply).permit(:content, :user_id, :critique_id)
  end
end

app/controllers/api/texts_controller.rb
class Api::TextsController < ApplicationController
  def index
    @texts = Text.includes(:critiques)
    render :index
  end
  
  def show
    @text = Text.find(params[:id])
    render :show
  end
  
  def create
    @text = Text.new(text_params)
    
    text_params[:content].gsub!(/\r/, '')
    text_params[:content].gsub!(/</, '')
    text_params[:content].gsub!(/>/, '')
    
    if @text.save
      render json: @text
    else
      render json: @text.errors.full_messages
    end
  end
  
  def destroy
    @text = Text.find(params[:id])
    
    if @text.destroy
      render json: @text
    else
      render json: @text.errors.full_messages
    end
  end
  
  private
  def text_params
    params.require(:text).permit(:title, :content, :user_id)
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    render :show
  end
  
  def update
    @user = User.find(params[:id])
    
    if @user.update(user_params)
      render json: @user
    else
      render json: @user.errors.full_messages
    end
  end
  
  private
  def user_params
    params.require(:user).permit(:filepicker_url)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user
  
  def login(user)
    user.reset_session_token
    session[:session_token] = user.session_token
  end
  
  def current_user
    return nil if session[:session_token].nil?
    @current_user ||= User.find_by_session_token(session[:session_token])
  end
  
  def require_current_user
    redirect_to new_user_url unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )
    
    if user
      login(user)
      redirect_to root_url
    else
      flash[:errors] = ["Invalid credentials"]
      redirect_to new_user_url
    end
  end
  
  def destroy
    current_user.reset_session_token
    session[:session_token] = nil
    redirect_to new_user_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  before_action :require_current_user

  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/critiques_helper.rb
module CritiquesHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wordshop</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
		<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Special+Elite&text=wordshop">
</head>
<body>
	
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  	<div class="container-fluid">
			<a href="/" class="navbar-brand">wordshop</a>
			<div class="btngrp" role="group">  			  
				
				<% if current_user %>
					<button type="button" class="btn btn-default" data-container="nav" 
					data-toggle="popover" data-placement="bottom" data-trigger="focus" 
					data-title="Tips" 
					data-content="1) Click on highlighted words to see their existing critique. 2) You can add inline critiques to any text except your own. Just highlight a piece of text and a form will appear, ready to accept your feedback. Please note that overlapping critiques are not allowed. 3) You can also leave general comments (not inline) on any text, or replies on any critique. 4) If you have a change of heart, you can always delete your own texts, critiques, replies, and comments.">
					?</button>
				
					<a href="/#" class="btn btn-default">Browse</a>
					<a href="/#texts/new" class="btn btn-default">Create text</a>
					<a class="btn btn-default" href="/#users/<%= current_user.id %>">
						<%= current_user.username %>
					</a>				
					<%= button_to "Sign Out", session_url, method: :delete, class: 'btn btn-default' %>
				<% else %>
					<form action="<%= session_url %>" method="POST" class="navbar-form" id="sign-in">

						<input type="hidden"
								name="authenticity_token"
								value="<%= form_authenticity_token %>">	

						<input type="text" name="user[username]" id="user_username" class="txti-small" placeholder="Username">
	
						<input type="password" name="user[password]" id="user_password" class="txti-small" placeholder="Password">
						<input type="submit" value="Sign In" class="btn-default">
					</form>						
				<% end %>
			</div>
    </div>
  	</nav>
	  <div class="container-fluid" style="padding-top:100px;">
			<ul>
			<% if flash[:errors] %>
				<% flash[:errors].each do |error| %>
				<div class="alert alert-danger" role="alert">
	
					<%= error %>
				</div>	
				<% end %>
			<% end %>
			</ul>
	<%= yield %>
	
		</div>
		<div id="footer"></div>
		
		<% if current_user %>
		<%= filepicker_js_include_tag %>			
		<script type="text/javascript">
		    window.currentUser = {
		        id : "<%= current_user.id %>",
					username: "<%= current_user.username %>"
		    };
				$('body').css({"background": "none", "background-color": 'white'});
				$(function () {
				  $('[data-toggle="popover"]').popover()
				});
			  filepicker.setKey("<%= ENV['FILEPICKER_API_KEY'] %>");
		</script>
		<% else %>
		<script>
			$('button#guest').on('click', function(){
				$('#user_username').val('Guest');
				$('#user_password').val('password');
				$('form#sign-in').submit();
		});
		</script>	
		<% end %>		

</body>
</html>